### ISSUE TITLE
Misleading example using USDC token

### ISSUE THREAD

**Issue by MidnightLightning** [ethstorage/web3url-doc#2]
In the examples listed at https://docs.web3url.io/basics/web3url-schema#examples, one of the examples given is

```web3://usdc.eth/balanceOf/0x1122...ff?returns=(uint256)```

The `usdc.eth` ENS domain is not actually pointed at the USDC token (and not owned by the Circle team who maintains USDC?), so is a misleading example to use. The real USDC token is `0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48`, while `usdc.eth` currently points to `0xc23446FAfA77Ae29f01C4F1bddF411e69eE4B8E4`

**Comment by qizhou** [comment]
This is an example to demonstrate the use of ENS to replace the address - it happens that `usdc.eth` is registered.

I think a quick fix will register an ENS name to points to USDC contract, but if Circle has an official one, that will be greatly helpful.

**Comment by qzhodl** [comment]
I searched ENS names for the official USDT, USDC, DAI, WETH and WBTC, and neither has an effective one.

**Comment by qzhodl** [comment]
Since the docs have been restructured, and the issue mentioned above has been removed, let's close the issue.

**Comment by MidnightLightning** [comment]
@qzhodl the misleading example is still present in the README of this code repo: https://github.com/ethstorage/web3url-doc?tab=readme-ov-file#fetch-an-usdc-balance

And, the docs have been restructured to move "examples" to https://docs.web3url.io/vision/examples, but that page uses `uniswap.eth` as an example of a "fully decentralized exchange" and `twitter.eth` as a way to "read a tweet". Both of those are not live "examples" that currently work. Those are both future goals/ideas of how things _could_ work in the future. It would be much better to provide examples that are live, working examples for people to browse.

**Comment by qizhou** [comment]
> @qzhodl the misleading example is still present in the README of this code repo: https://github.com/ethstorage/web3url-doc?tab=readme-ov-file#fetch-an-usdc-balance
> 
> And, the docs have been restructured to move "examples" to https://docs.web3url.io/vision/examples, but that page uses `uniswap.eth` as an example of a "fully decentralized exchange" and `twitter.eth` as a way to "read a tweet". Both of those are not live "examples" that currently work. Those are both future goals/ideas of how things _could_ work in the future. It would be much better to provide examples that are live, working examples for people to browse.

Thank you for pointing this out.  @qzhodl could you please assign an issue for this?

**Comment by qzhodl** [comment]
Reopen it because there is still a reference to usdc.eth in readme, I think we can replace it with web3://0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48/balanceOf/gitgatt.eth?returns=(uint256)

**Comment by iteyelmp** [comment]
It has been fixed
